### ISSUE TITLE
Deploy Curator in Zero cluster

### ISSUE THREAD

**Issue by gagansk** [operate-first/curator#63]
DoD:

* Deploy Curator in Zero cluster of the Operate First environment.
* At least one weekly, 5 daily reports should be generated for the Zero cluster before their scheduled maintenance on Aug 9th, 2021. 
* Run a custom query for the aggregated infrastructure report which has CPU time for a project/namespace.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200965343172825/1200984483371908) by [Unito](https://www.unito.io)

**Comment by skanthed** [comment]
Working with Humair to get enough resources to run our v0.4

PR to koku-metric-operator namespace quota linked
[https://github.com/operate-first/apps/pull/883](url)

Koku metric operator is restarting again and again. It's a timeout error that can be due to a high load or not enough resource allocation. Trying to resolve that.
